# Generated by Django 3.2.3 on 2021-09-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
