# Generated by Django 3.2.3 on 2021-09-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210916_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='user',
        ),
    ]
