# Generated by Django 3.2.3 on 2021-09-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_contactdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
    ]
